Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120

StringLiterals:
  Enabled: false

Documentation:
  Enabled: false


Metrics/BlockLength:
  ExcludedMethods: ["describe", "context", "feature"]
